# Generated by Django 4.0 on 2022-05-11 10:13

import apps.media_center.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('security_permission', models.CharField(choices=[('admin_only', 'admin_only'), ('public', 'public'), ('client', 'client')], default='public', max_length=100)),
                ('uploaded_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to=apps.media_center.utils.path_and_rename)),
                ('remote_url', models.URLField(null=True)),
                ('original_type', models.CharField(editable=False, max_length=100, null=True)),
                ('size', models.IntegerField(editable=False, null=True)),
                ('length', models.DurationField(null=True)),
                ('alternative_text', models.TextField(null=True)),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_media', to='authentication.systemuser')),
            ],
            options={
                'db_table': 'media',
            },
        ),
    ]
