# Generated by Django 4.0 on 2022-05-11 10:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('media_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('widget_type', models.CharField(choices=[('slider', 'slider'), ('input_number', 'input_number'), ('input_text', 'input_text'), ('single_choice', 'single_choice'), ('multiple_choice', 'multiple_choice'), ('dropdown', 'dropdown')], max_length=100)),
                ('code', models.CharField(default='', editable=False, max_length=200)),
                ('text', models.TextField()),
                ('text_vi', models.TextField(null=True)),
                ('hint', models.TextField(null=True)),
                ('hint_vi', models.TextField(null=True)),
                ('order', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'question',
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='QuestionClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_vi', models.TextField()),
                ('order', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('related_to', models.CharField(max_length=100, verbose_name=(('investment', 'investment'), ('company', 'company')))),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'question_class',
                'ordering': ('related_to', 'order'),
            },
        ),
        migrations.CreateModel(
            name='QuestionDefaultAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('answer_text_vi', models.TextField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_answer_set', to='dashboard.question')),
            ],
            options={
                'db_table': 'question_default_answer',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.questionclass'),
        ),
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('verification_status', models.CharField(choices=[('pre_pending', 'pre_pending'), ('done', 'done'), ('failed', 'failed')], default='pre_pending', max_length=100, null=True)),
                ('service_data', models.JSONField(default=dict, null=True)),
                ('failed_reason', models.TextField(null=True)),
                ('card_back', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identity_card_back', to='media_center.media')),
                ('card_front', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identity_card_front', to='media_center.media')),
                ('selfie_photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identity_selfie', to='media_center.media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='identity', to='authentication.systemuser')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
