version: '3.3'
services:
  backend_service:
    build:
      context: .
    container_name: 'backend_service_2'
    restart: always
    command: gunicorn --bind :8000  EarlyBird.wsgi:application
    ports:
      - 9000:8000
    volumes:
      - .:/eb_system
      - ./static:/static
      - ./run/media:/eb_system/run/media

    env_file:
      - configs/django/production.env
    networks:
      - database_network
    depends_on:
      - database_service

  database_service:
    image: postgres:14.2
    restart: always
    container_name: 'database_service_2'
    volumes:
      - database_volume:/var/lib/postgresql/data
    env_file:
      - configs/db/production.env
    ports:
      - 5400:5432
    networks:
      - database_network

networks:
  database_network:
    driver: bridge

volumes:
  database_volume:
  static_volume:
  media_volume:
  backup_volume:
