# Generated by Django 4.0 on 2022-05-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='type')),
                ('info', models.TextField()),
                ('data', models.TextField(blank=True, null=True)),
                ('path', models.URLField(blank=True, null=True)),
                ('when', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('html', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Error',
                'verbose_name_plural': 'Errors',
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('db_file_size', models.FloatField(null=True)),
                ('media_file_size', models.FloatField(null=True)),
                ('db_file', models.CharField(max_length=255, null=True)),
                ('media_file', models.CharField(max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='authentication.systemuser')),
            ],
            options={
                'db_table': 'system_backup',
            },
        ),
    ]
