# Generated by Django 4.0 on 2022-05-11 10:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('dashboard', '0001_initial'),
        ('media_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('investor_id_number', models.TextField()),
                ('investor_name', models.TextField()),
                ('investor_email', models.TextField()),
                ('investor_address', models.TextField()),
                ('investor_phone', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invest_profile', to='authentication.systemuser')),
            ],
            options={
                'db_table': 'investment_profile',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='InvestmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('attachment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_details_media', to='media_center.media')),
                ('invest_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invest_details', to='investment.investmentprofile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.question')),
            ],
            options={
                'db_table': 'investment_details',
                'ordering': ('id',),
            },
        ),
    ]
