# Generated by Django 4.0 on 2022-06-12 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('company', '0011_alter_companypresent_phone_number_and_more'),
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='investment_participation', to='company.company')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.systemuser')),
            ],
            options={
                'db_table': 'investment_participation',
            },
        ),
    ]
