# Generated by Django 4.0 on 2022-06-29 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_companypresent_phone_number_and_more'),
        ('investment', '0003_alter_investmentparticipation_investment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentparticipation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_participation', to='company.company'),
        ),
    ]
