# Generated by Django 4.0 on 2022-06-29 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_alter_investmentparticipation_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentparticipation',
            name='investment_amount',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(50000000), django.core.validators.MinValueValidator(10000)]),
        ),
    ]
