# Generated by Django 4.0 on 2022-07-20 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('investment', '0005_alter_investmentparticipation_investment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentparticipation',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participated_companies', to='authentication.systemuser'),
        ),
    ]
