# Generated by Django 4.0 on 2022-05-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypresent',
            name='Legal_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
