# Generated by Django 4.0 on 2022-05-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_companypresent_legal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypresent',
            name='Legal_name',
        ),
    ]
