# Generated by Django 4.0 on 2022-05-11 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_companypresent_legal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypresentdocuments',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companypresent'),
        ),
    ]
