# Generated by Django 4.0 on 2022-05-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companypresentdocuments_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypresent',
            name='is_hot',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companypresent',
            name='is_trends',
            field=models.BooleanField(default=True),
        ),
    ]
