# Generated by Django 4.0 on 2022-05-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companypresent_abstract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companypresent',
            old_name='is_trends',
            new_name='is_trending',
        ),
    ]
