# Generated by Django 4.0 on 2022-05-14 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_rename_is_trends_companypresent_is_trending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypresentdocuments',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='present_documents', to='company.companypresent'),
        ),
    ]
