# Generated by Django 4.0 on 2022-05-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_companypresentdocuments_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypresent',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=100),
        ),
    ]
