# Generated by Django 4.0 on 2022-05-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_companypresent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypresent',
            name='phone_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='companypresent',
            name='price_per_share',
            field=models.DecimalField(decimal_places=4, max_digits=30, null=True),
        ),
    ]
