# Generated by Django 4.0 on 2022-10-17 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0001_initial'),
        ('company', '0011_alter_companypresent_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='registration_docs_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_doc_media_1', to='media_center.media'),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_docs_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_doc_media_2', to='media_center.media'),
        ),
        migrations.AddField(
            model_name='company',
            name='youtube_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
