# Generated by Django 4.0 on 2022-10-17 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0001_initial'),
        ('company', '0012_company_registration_docs_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypresent',
            name='cover_image_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_present_preview_1', to='media_center.media'),
        ),
        migrations.AddField(
            model_name='companypresent',
            name='cover_image_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_present_preview_2', to='media_center.media'),
        ),
        migrations.AddField(
            model_name='companypresent',
            name='youtube_url',
            field=models.TextField(null=True),
        ),
    ]
