# Generated by Django 4.0 on 2022-10-17 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0001_initial'),
        ('company', '0014_companypresent_youtubeurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypresent',
            name='cover_image1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_present_preview1', to='media_center.media'),
        ),
        migrations.AddField(
            model_name='companypresent',
            name='cover_image2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_present_preview2', to='media_center.media'),
        ),
    ]
