"""
Django settings for EarlyBird project.

Generated by 'django-admin startproject' using Django 4.0.1.

ForENV DEBIAN_FRONTEND noninteracti more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from os.path import join
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# sys.path.append(normpath(join(BASE_DIR, 'apps')))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!

# Application definition

SECRET_KEY = '3=92xbzk^y@a*ve27oc!(l_jrlu$hikpf!w75s@h_4-nua!02v'
EXTRA_SECRET_KEY = 'v72m=(#0dhvw_a=21+cd)#n+u_roc@vn2#@@#if5jxn3%t^%%^'
GRAPH_SECRET_KEY = 'aw-%6se6z^fgj6a%(2!3-l9w8xffkfc_#0w4(bwhr-vv_e=_k6'

DEFAULT_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

]
THIRD_PARTY = [
    "corsheaders",
    'rest_framework',
'django_filters',
    'rest_framework_simplejwt.token_blacklist',
    'utils.apps.UtilsConfig',
    "rest_framework_api_key",
    'dbbackup'

]

PRIMARY_APPS = [
    'apps.investment.apps.InvestmentConfig',
    # 'apps.questionnaire.apps.QuestionnaireConfig',
    'apps.authentication.apps.AuthenticationConfig',
    'apps.system_settings.apps.SystemSettingsConfig',
    'apps.company.apps.CompanyConfig',
    'apps.media_center.apps.MediaCenterConfig',
    'apps.dashboard.apps.DashboardConfig',
    'apps.learning_board.apps.LearningBoardConfig',
    'apps.system_monitor.apps.SystemMonitorConfig',
    'apps.payment.apps.PaymentConfig',
    'apps.challenge.apps.ChallengeConfig',
    # 'apps.system_backup.apps.SystemBackupConfig',
]
INSTALLED_APPS = DEFAULT_APPS + THIRD_PARTY + PRIMARY_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EarlyBird.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EarlyBird.wsgi.application'

AUTHENTICATION_BACKENDS = [
    'apps.authentication.backend.MyBackend',

]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

FILTERS_DEFAULT_LOOKUP_EXPR = 'icontains'

"""
Auth models
"""

AUTH_USER_MODEL = 'authentication.SystemUser'

"""
Api Docs
"""

JAZZMIN_SETTINGS = {
    "site_title": "Library Admin",
    "site_header": "Technicians Dashboard",
    "site_brand": "Technicians Dashboard",
    "site_logo": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "EarlyBird Service",
    "copyright": "EarlyBird",
    "search_model": None,
    "user_avatar": None,
    "topmenu_links": [

    ],
    "usermenu_links": None,
    "hide_apps": ['auth', 'token_blacklist'],
    "hide_models": [],
    "order_with_respect_to": ["auth", "books", "books.author", "books.book"],
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "changeform_format": "horizontal_tabs",
    "language_chooser": False,
}

"""
static files 
"""
STATIC_URL = 'static/'
STATIC_ROOT = join(BASE_DIR, 'static')

"""
Initial Data 
"""
INITIAL_DATA_PATH = 'run/fixtures/initial_data/'

"""
FireBase Settings
"""
FIREBASE_API_KEY = 'AIzaSyDZKDoP4UUgEjR0_UmDyGxH-_eoWE5w29k'
# FIREBASE_API_KEY = 'AIzaSyBb2cYHm5L3y6UnC4v68THFfpvbCWZBKhc'

SESSION_COOKIE_HTTPONLY = True

JUMIO_SERVICE_CALLBACK_IP = [
    # US data center:
    '34.202.241.227',
    '34.226.103.119',
    '34.226.254.127',
    '52.52.51.178',
    '52.53.95.123',
    '54.67.101.173',

    # EU data center:
    '34.253.41.236',
    '35.157.27.193',
    '52.48.0.25',
    '52.57.194.92',
    '52.58.113.86',
    '52.209.180.134',

    # SGP data center:
    '3.0.109.121',
    '52.76.184.73',
    '52.77.102.92'
]

API_KEY_CUSTOM_HEADER = "HTTP_API_KEY"

"""
Backup setting
"""
BACKUP_PATH = f'{BASE_DIR}/run/backups_files/'

DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': BACKUP_PATH}

# BACKUP_FILE_PREFIX = 'Flocks-Backup'
# BACKUP_URL = 'backups_files'
# BACKUP_KEY = b'yiIjyF25wF8qTKROPW_B1MMAbJkBnMw3wuQ4h9l7n04='
DBBACKUP_FILENAME_TEMPLATE = 'Flocks-{datetime}.{extension}'
BACKUP_FILE_PREFIX = 'FlocksAi'
BACKUP_KEY = b'yiIjyF25wF8qTKROPW_B1MMAbJkBnMw3wuQ4h9l7n04='
BACKUP_URL = 'backups_file'

"""
Stripe Secret Key 
"""
# TODO move strip api key to env file
STRIPE_LIVE_SECRET_KEY = os.environ.get("STRIPE_LIVE_SECRET_KEY", "<your secret key>")
STRIPE_TEST_SECRET_KEY = os.environ.get("STRIPE_TEST_SECRET_KEY", "sk_test_51L4KnuK1X9tURHXdco69ZNGR8dTEe9VIP3EBPz4AqD0rRglNdiBFYNc3xeviOzMFyJ001MmtgcbOLba2gr5THGQm00GtPg9ym5")
STRIPE_SECRET_KEY = 'sk_test_51L4KnuK1X9tURHXdco69ZNGR8dTEe9VIP3EBPz4AqD0rRglNdiBFYNc3xeviOzMFyJ001MmtgcbOLba2gr5THGQm00GtPg9ym5'
ENDPOINT_SECRET = 'whsec_9edlCe07VmZ5ieAgyplLlbHnLYk2y0kU'
