# Generated by Django 4.0 on 2022-06-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('name', models.TextField()),
                ('icon', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'challenge_day',
            },
        ),
    ]
