# Generated by Django 4.0 on 2022-06-21 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('title_vi', models.TextField(null=True)),
                ('description', models.TextField()),
                ('description_vi', models.TextField()),
            ],
            options={
                'db_table': 'challenge',
            },
        ),
        migrations.CreateModel(
            name='ChallengeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('title_vi', models.TextField(null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge')),
            ],
            options={
                'db_table': 'challenge_question',
            },
        ),
        migrations.AlterModelOptions(
            name='challengeday',
            options={'ordering': ('day_number',)},
        ),
        migrations.AddField(
            model_name='challengeday',
            name='name_vi',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='challengeday',
            name='icon',
            field=models.ImageField(upload_to='public/'),
        ),
        migrations.CreateModel(
            name='ChallengeQuestionDefaultAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('answer_text_vi', models.TextField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_answer_set', to='challenge.challengequestion')),
            ],
            options={
                'db_table': 'challenge_question_default_answer',
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenge_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.challengeday'),
        ),
    ]
