# Generated by Django 4.0 on 2022-06-21 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_challengequestion_answer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengequestion',
            name='question_type',
            field=models.CharField(choices=[('link', 'link'), ('attachment', 'attachment'), ('question_answer', 'question_answer')], default='question_answer', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChallengeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.challengequestion')),
            ],
        ),
    ]
