# Generated by Django 4.0 on 2022-06-21 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('challenge', '0004_challengequestion_question_type_challengeanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeanswer',
            name='attachment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='challengeanswer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_challenge_ans', to='authentication.systemuser'),
        ),
    ]
