# Generated by Django 4.0 on 2022-06-21 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_challengeanswer_attachment_challengeanswer_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='challengeanswer',
            table='challenge_answer',
        ),
    ]
