# Generated by Django 4.0 on 2022-06-22 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_alter_challengeanswer_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('passed', 'passed'), ('pending', 'pending'), ('failed', 'failed')], default='pending', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='challengequestion',
            name='challenge_type',
            field=models.CharField(choices=[('link', 'link'), ('attachment', 'attachment'), ('question_answer', 'question_answer')], default='link', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challengequestion',
            name='hint',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='challengequestion',
            name='hint_vi',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='challenge.challengeday'),
        ),
        migrations.AlterField(
            model_name='challengequestion',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_question', to='challenge.challenge'),
        ),
        migrations.AlterField(
            model_name='challengequestion',
            name='question_type',
            field=models.CharField(choices=[('input_text', 'input_text'), ('boolean', 'boolean'), ('single_choice', 'single_choice')], max_length=100),
        ),
        migrations.DeleteModel(
            name='ChallengeAnswer',
        ),
        migrations.AddField(
            model_name='challengeresult',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge'),
        ),
    ]
