# Generated by Django 4.0 on 2022-06-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_challengeresult_challengequestion_challenge_type_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='challengeresult',
            table='challenge_result',
        ),
    ]
