# Generated by Django 4.0 on 2022-06-22 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_alter_challengeresult_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('attachment', models.TextField(null=True)),
                ('challenge_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_user_answer', to='challenge.challengeresult')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.challengequestion')),
            ],
            options={
                'db_table': 'challenge_user_answer',
            },
        ),
    ]
