# Generated by Django 4.0 on 2022-06-22 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('challenge', '0009_challengequestionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeresult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_challenge_ans', to='authentication.systemuser'),
        ),
    ]
