# Generated by Django 4.0 on 2022-06-22 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0001_initial'),
        ('challenge', '0010_challengeresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengequestionanswer',
            name='attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_ans_attach', to='media_center.media'),
        ),
    ]
