# Generated by Django 4.0 on 2022-06-23 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0011_alter_challengequestionanswer_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeresult',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_result', to='challenge.challenge'),
        ),
    ]
