# Generated by Django 4.0 on 2022-06-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0012_alter_challengeresult_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengequestionanswer',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
