# Generated by Django 4.0 on 2022-07-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0013_alter_challengequestionanswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeday',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
