# Generated by Django 4.0 on 2022-07-13 09:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0014_alter_challengeday_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengequestion',
            name='answer_text',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None),
        ),
    ]
