# Generated by Django 4.0 on 2022-07-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0015_alter_challengequestion_answer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeday',
            name='name',
        ),
        migrations.RemoveField(
            model_name='challengeday',
            name='name_vi',
        ),
    ]
