# Generated by Django 4.0 on 2022-06-15 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('object', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('balance', models.DecimalField(decimal_places=20, max_digits=30)),
                ('created', models.DateTimeField(null=True)),
                ('currency', models.TextField(null=True)),
                ('default_source', models.TextField(null=True)),
                ('delinquent', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('discount', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('invoice_prefix', models.TextField(null=True)),
                ('invoice_settings', models.JSONField(null=True)),
                ('livemode', models.BooleanField()),
                ('metadata', models.JSONField(null=True)),
                ('name', models.TextField(null=True)),
                ('next_invoice_sequence', models.IntegerField(null=True)),
                ('phone', models.TextField(null=True)),
                ('preferred_locales', models.JSONField(null=True)),
                ('shipping', models.TextField(null=True)),
                ('tax_exempt', models.TextField(null=True)),
                ('test_clock', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stripe_customer', to='authentication.systemuser')),
            ],
            options={
                'db_table': 'stripe_customer',
                'ordering': ('id',),
            },
        ),
    ]
