# Generated by Django 4.0 on 2022-06-15 06:54

from django.db import migrations
import utils.dj_stripe_fields


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='created',
            field=utils.dj_stripe_fields.StripeDateTimeField(null=True),
        ),
    ]
