# Generated by Django 4.0 on 2022-06-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_stripecustomer_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecustomer',
            name='created',
        ),
    ]
