# Generated by Django 4.0 on 2022-06-15 07:16

from django.db import migrations
import utils.dj_stripe_fields


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_stripecustomer_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='created',
            field=utils.dj_stripe_fields.StripeDateTimeField(null=True),
        ),
    ]
