# Generated by Django 4.0 on 2022-06-16 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_stripecustomer_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCharge',
            fields=[
                ('amount', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('amount_captured', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('amount_refunded', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('application', models.TextField(null=True)),
                ('application_fee', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('application_fee_amount', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('balance_transaction', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('billing_details', models.JSONField(null=True)),
                ('calculated_statement_descriptor', models.TextField(null=True)),
                ('captured', models.TextField(null=True)),
                ('created', models.DateTimeField(null=True)),
                ('currency', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('destination', models.TextField(null=True)),
                ('dispute', models.TextField(null=True)),
                ('disputed', models.TextField(null=True)),
                ('failure_balance_transaction', models.TextField(null=True)),
                ('failure_code', models.TextField(null=True)),
                ('failure_message', models.TextField(null=True)),
                ('fraud_details', models.TextField(null=True)),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('invoice', models.TextField(null=True)),
                ('livemode', models.TextField(null=True)),
                ('metadata', models.TextField(null=True)),
                ('object', models.TextField(null=True)),
                ('on_behalf_of', models.TextField(null=True)),
                ('order', models.TextField(null=True)),
                ('outcome', models.JSONField()),
                ('paid', models.TextField(null=True)),
                ('payment_intent', models.TextField(null=True)),
                ('payment_method', models.TextField(null=True)),
                ('payment_method_details', models.JSONField()),
                ('receipt_email', models.TextField(null=True)),
                ('receipt_number', models.TextField(null=True)),
                ('receipt_url', models.TextField(null=True)),
                ('refunded', models.TextField(null=True)),
                ('refunds', models.TextField(null=True)),
                ('review', models.TextField(null=True)),
                ('shipping', models.TextField(null=True)),
                ('source', models.JSONField(null=True)),
                ('source_transfer', models.TextField(null=True)),
                ('statement_descriptor', models.TextField(null=True)),
                ('statement_descriptor_suffix', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
                ('transfer_data', models.TextField(null=True)),
                ('transfer_group', models.TextField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.stripecustomer')),
            ],
        ),
    ]
