# Generated by Django 4.0 on 2022-06-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_stripecharge_balance_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecharge',
            name='captured',
            field=models.BooleanField(null=True),
        ),
    ]
