# Generated by Django 4.0 on 2022-06-16 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_companypresent_phone_number_and_more'),
        ('payment', '0007_alter_stripecharge_captured'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecharge',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='company.company'),
        ),
    ]
