# Generated by Django 4.0 on 2022-06-29 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_stripecharge_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecustomer',
            name='user',
        ),
        migrations.DeleteModel(
            name='StripeCharge',
        ),
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
    ]
