# Generated by Django 4.0 on 2022-06-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='extraData',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='orderId',
            new_name='order_info',
        ),
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='orderInfo',
            new_name='order_type',
        ),
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='orderType',
            new_name='partner_code',
        ),
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='partnerCode',
            new_name='pay_type',
        ),
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='payType',
            new_name='request_id',
        ),
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='requestId',
            new_name='response_time',
        ),
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='responseTime',
            new_name='result_code',
        ),
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='resultCode',
            new_name='trans_id',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='transId',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='extra_data',
            field=models.JSONField(null=True),
        ),
    ]
