# Generated by Django 4.0 on 2022-06-29 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('payment', '0014_onlinetransaction_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinetransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_transaction', to='authentication.systemuser'),
        ),
    ]
