# Generated by Django 4.0 on 2022-07-20 09:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0005_alter_investmentparticipation_investment_amount'),
        ('company', '0011_alter_companypresent_phone_number_and_more'),
        ('authentication', '0002_initial'),
        ('payment', '0016_rename_participant_id_onlinetransaction_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPaymentEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bizType', models.TextField()),
                ('data', models.JSONField(default=dict, null=True)),
                ('bizId', models.TextField()),
                ('bizStatus', models.TextField()),
            ],
            options={
                'db_table': 'binance_event',
            },
        ),
        migrations.CreateModel(
            name='CryptoPaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('platform', models.TextField()),
                ('amount', models.TextField()),
                ('currency', models.TextField()),
                ('bizType', models.TextField()),
                ('prepay_order_id', models.TextField()),
                ('status', models.TextField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crypto_transaction', to='company.company')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='investment.investmentparticipation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_crypto_transaction', to='authentication.systemuser')),
            ],
            options={
                'db_table': 'crypto_history_list',
            },
        ),
    ]
