# Generated by Django 4.0 on 2022-05-11 10:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.TextField(null=True, unique=True, validators=[django.core.validators.EmailValidator])),
                ('auth_phone', models.CharField(max_length=16, null=True, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(default='client', max_length=100)),
                ('headline', models.TextField(null=True)),
                ('bio', models.TextField(null=True)),
                ('angel', models.TextField(null=True)),
                ('facebook', models.TextField(null=True)),
                ('twitter', models.TextField(null=True)),
                ('linkedIn', models.TextField(null=True)),
                ('website', models.TextField(null=True)),
                ('is_verified', models.BooleanField()),
                ('first_name', models.CharField(max_length=150, null=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, null=True, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'SystemUser',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='CustomTokenManagement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('token_type', models.CharField(choices=[('email_reset_password', 'email_reset_password'), ('email_verify', 'email_verify')], max_length=100)),
                ('is_usable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'custom_token_management',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.TextField(choices=[('google', 'google'), ('twitter', 'twitter'), ('apple', 'apple'), ('facebook', 'facebook')])),
                ('uid', models.TextField()),
                ('email', models.TextField(null=True)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('extra_data', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Social Accounts',
                'db_table': 'social_account',
                'ordering': ['-user'],
            },
        ),
        migrations.CreateModel(
            name='SocialToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='token')),
                ('refresh_token', models.TextField(blank=True, verbose_name='token secret')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.socialaccount')),
            ],
            options={
                'verbose_name': 'social application token',
                'verbose_name_plural': 'social application tokens',
            },
        ),
    ]
