# Generated by Django 4.0 on 2022-05-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_settings', '0001_initial'),
        ('authentication', '0001_initial'),
        ('media_center', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialtoken',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_settings.socialapp'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_account', to='authentication.systemuser'),
        ),
        migrations.AddField(
            model_name='customtokenmanagement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.systemuser'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_avatar', to='media_center.media'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='cover_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cover_photo', to='media_center.media'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('provider', 'uid')},
        ),
    ]
